### PR TITLE
add label field to crystal forging

### PR DESCRIPTION
**Pull request by mixmix**
image

Things I'd like reviewed:
- the label down the left (should it be "Label" or "Description")
- placeholder text?
- **should we put a character limit in here?** :fire: 

The last is the most important IMO

### CODE REVIEW

**Comment by ameba23** [comment]
ps. have you already done the other end (display the label after recombining)?  cos if you haven't, i've moved the recombining-related-functions to another file in the branch im working on, so that its also accessible to the 'forwards-index'.  so it might create less conflicts if one of us first merges other other's branch (or something like that...).  although would probably be a pretty simple one to resolve anyway.

**Comment by mixmix** [comment]
Oh i didn't do the display part.... I think that's in your domain. Maybe
unpack and just show the label if it exists?

**Comment by mixmix** [comment]
Nice catch on that validating the combined length. I've added that now : 
image

that counter live updates which I hope means the concise message will make sense - as soon as they touch the label, that counter changes... (like twitter limit counter)

**Comment by mixmix** [comment]
@ameba23 thanks for the review. I'm implicitly reading that now I've added that validation this is ok to merge?

If you feel like it needs more attention happy to revisit. I'm going to leave displaying the labels that come out to you

**Pull request merged**
