### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by mixmix**
- newcrystal / load quiries/ test setup

cc @ameba23 @KGibb8 
if you'd like to review this that would be great

### CODE REVIEW

**Comment by mixmix** [comment]
Here's a breakdown of the layout: 
```

├── package.json
├── package-lock.json
├── plugs
│   ├── app
│   │   ├── DarkCrystal.mcss
│   │   └── index.js
│   ├── index.js
│   ├── router
│   │   └── index.js
│   └── styles
│       └── index.js
├── README.md
└── views
    ├── component
    │   ├── recipients.js
    │   └── recipients.mcss
    ├── new.js
    ├── new.mcss
    └── new.test.js
```

## `/views`

This is basically the views of an MVC setup, except the views have some observeable logic, and we will also pass in an copy of the `scuttle-dark-crystal` helper in which the views will be able to use to call things to happen.

These views use `electro` to do testing - it's a version of electron which dominic stripped down / wrapped to make it more like a unix app. Bascially you can go `electro views/new.test.js` and it opens. The test file hands in mock / dummy data  + deps which makes the reloading of this hella fast.

I've left the command at the to run at the top of the `new.test.js` to start it up. Note `npx` is a new command which lets you run an installed dep from the command like like an executable. This prevents us having to install `electro` globally. (don't worry so much about this particular detail)

## `plugs/`

This is a collection of files which take the "dumb" views and provide them all the deps they need to run in the particular context of patchbay. See `plugs/app/index.js` first (this exports `app.page.darkCrystal`). If we put more in the app folder I will split out `plugs/app/page/folder.js` and the other patchbay modules / plugs (things which plug into other things in patchbay).

The `router` folder adds to the patchbay routes
The `styles` folder has a function which scrapes this whole repo for `*.mcss` files, then hands those up into patchbay which then compiles that into css and inserts it into the DOM.

---

## This PR

there's a lot going on in here, but a lot of it has been copied from other projects, so know that I didn't write all this in a couple of days !!  It's the result of a lot of iteration, and some meditate refactoring on weekends. It can def still be improved and it's just a very rough starting point.

If you want to try what I've got running in Patchbay, clone both repos down, then `npm link` them together (this creates a symlink which means we don't need to publish modules to try them out). Steps:
1. clone patchbay-dark-crystal
2. change to this branch, and `npm install`. Run `npm link` to register this as a linkable endpoint
3. clone and install patchbay in another folder (remember to run `npm run rebuild`). You need node 8 (9 has problems at the moment)
4. run `npm link patchbay-dark-crystal`
  - you should see something like the following which looks like a symlink trail:
```
/home/mix/projects/SSBC/patchbay/node_modules/patchbay-dark-crystal -> /home/mixmix/.nvm/versions/node/v8.11.3/lib/node_modules/patchbay-dark-crystal -> /home/mix/projects/SSBC/DARK-CRYSTAL/patchbay-dark-crystal
```
5. start patchbay `npm start`

**Comment by mixmix** [comment]
this branch is getting quite large.
I'm going to merge it, but happy to discuss parts of this.

would like to know if you have any questions about the intro I wrote about. Or just to know you saw it @ameba23 + @KGibb8

**Comment by dan-mi-sun** [comment]
Mix I have read the README and it made sense to me, but I'm not as deep in
the code so my :thumbsup: should be considered a shallow one.

**Comment by dan-mi-sun** [comment]
@mixmix for step 4 I had to run

`npm link /home/user/Lib/patchbay-dark-crystal`

or the output from step 2.

**Comment by dan-mi-sun** [comment]
@mixmix for step 5 worth noting that one needs to 

`git checkout dark_crystal` branch within patchbay before running `npm start`

**Comment by ameba23** [comment]
Just gotten around to getting this running.  Its looking pretty smart!   Love it!  Good work @mixmix!

**Pull request merged**
